version: "3"

services:
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  Cerebellum:
    image: public.ecr.aws/q8e0a8z0/cerebellum_server_dev:latest
    container_name: Cerebellum
    ports:
      - "8001:8001"
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
      - AWS_REGION=us-east-1
      - API_KEY=sample_key
      - DYNAMODB_MESSAGES_TABLE_NAME=messages
      - DYNAMODB_CHANNELS_TABLE_NAME=channels

    depends_on:
      - dynamodb-local
      - redis
    links:
      - dynamodb-local
      - redis
